#!/bin/bash
#
# Reset the truffle dev params
# And modify .env.dev.local

# check ganache-cli is running
PID=$(ps aux | grep [n]ode.*ganache | awk '{print $2}')

# may start ganache (manually)
[[ ! $PID =~ ^-?[0-9]+$ ]] && echo "ganache not running" && exit

# Compile to be sure of new changes
truffle compile

# migrate from scratch (create file if needed)
touch .env.truffle
truffle migrate --reset --network development > .env.truffle

# get the new address
NEW_ADDR=$(cat .env.truffle | grep 'OmniCAT:' | awk '{print $2}')

# change out the old address
# operation clobbers prev file contents via single '>'
touch .env.dev.local
echo "OMNICAT_CONTRACT_ADDRESS=$NEW_ADDR" > .env.dev.local

# update the contract abi'
echo "OMNICAT_CONTRACT_ABI=$(npx solcjs --abi contracts/OmniCAT.sol)" >> .env.dev.local

# remove generated abi file from project root
rm contracts_OmniCAT_sol_OmniCAT.abi
